// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALncYDGvVT6JaoEWvpYu0NWQO_XV43utE',
    appId: '1:13059:web:placeholder', // TODO: Update with actual App ID
    messagingSenderId: '123456789', // TODO: Update with actual Sender ID
    projectId: 'bulletin-bot-13059',
    authDomain: 'bulletin-bot-13059.firebaseapp.com',
    databaseURL: 'https://bulletin-bot-13059-default-rtdb.firebaseio.com',
    storageBucket: 'bulletin-bot-13059.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALncYDGvVT6JaoEWvpYu0NWQO_XV43utE',
    appId: '1:13059:android:placeholder',
    messagingSenderId: '123456789',
    projectId: 'bulletin-bot-13059',
    databaseURL: 'https://bulletin-bot-13059-default-rtdb.firebaseio.com',
    storageBucket: 'bulletin-bot-13059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALncYDGvVT6JaoEWvpYu0NWQO_XV43utE',
    appId: '1:13059:ios:placeholder',
    messagingSenderId: '123456789',
    projectId: 'bulletin-bot-13059',
    databaseURL: 'https://bulletin-bot-13059-default-rtdb.firebaseio.com',
    storageBucket: 'bulletin-bot-13059.appspot.com',
    iosBundleId: 'com.example.bahalana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALncYDGvVT6JaoEWvpYu0NWQO_XV43utE',
    appId: '1:13059:macos:placeholder',
    messagingSenderId: '123456789',
    projectId: 'bulletin-bot-13059',
    databaseURL: 'https://bulletin-bot-13059-default-rtdb.firebaseio.com',
    storageBucket: 'bulletin-bot-13059.appspot.com',
    iosBundleId: 'com.example.bahalana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALncYDGvVT6JaoEWvpYu0NWQO_XV43utE',
    appId: '1:13059:windows:placeholder',
    messagingSenderId: '123456789',
    projectId: 'bulletin-bot-13059',
    authDomain: 'bulletin-bot-13059.firebaseapp.com',
    databaseURL: 'https://bulletin-bot-13059-default-rtdb.firebaseio.com',
    storageBucket: 'bulletin-bot-13059.appspot.com',
  );
}